[tool.poetry]
name = "gmc_code"
version = "0.1.0"
description = "Pytorch implementation of the GMC method."
authors = ["Anonymous"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
