# Pretrained models for the Unsupervised Experiment (Section 5.1)

# GMC
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1Ml1Z4VgMmVmBnUvqWG8sZE-EWKc6V6mJ' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1Ml1Z4VgMmVmBnUvqWG8sZE-EWKc6V6mJ" -O ./unsupervised/trained_models/gmc_mhd_model.pth.tar && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1bqjrDmF1ft6rB8O8J1dfpUg1kbmd7ezn' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1bqjrDmF1ft6rB8O8J1dfpUg1kbmd7ezn" -O ./unsupervised/trained_models/down_gmc_mhd_model.pth.tar && rm -rf /tmp/cookies.txt

# MVAE
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1TnB5AE68KoxU96u3dU3qDVdOki7d5IFJ' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1TnB5AE68KoxU96u3dU3qDVdOki7d5IFJ" -O ./unsupervised/trained_models/mvae_mhd_model.pth.tar && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1hoGy1XiwITq6I1TEHRverwsnn1GkERq2' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1hoGy1XiwITq6I1TEHRverwsnn1GkERq2" -O ./unsupervised/trained_models/down_mvae_mhd_model.pth.tar && rm -rf /tmp/cookies.txt

# MMVAE
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1i2e3XceZD16B0YNrWRS2z2G-2XHBX4BA' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1i2e3XceZD16B0YNrWRS2z2G-2XHBX4BA" -O ./unsupervised/trained_models/mmvae_mhd_model.pth.tar && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1Mx8PS4UyCkfeb03-meglfQhBAug2D0Mk' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1Mx8PS4UyCkfeb03-meglfQhBAug2D0Mk" -O ./unsupervised/trained_models/down_mmvae_mhd_model.pth.tar && rm -rf /tmp/cookies.txt

# MFM
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1U9cfit_8-c4e7A8tpwLVLvpS11jxFwI-' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1U9cfit_8-c4e7A8tpwLVLvpS11jxFwI-" -O ./unsupervised/trained_models/mfm_mhd_model.pth.tar && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=11PHwTr8iQ2rlzuecDabQWyCPGijS1Zwy' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=11PHwTr8iQ2rlzuecDabQWyCPGijS1Zwy" -O ./unsupervised/trained_models/down_mfm_mhd_model.pth.tar && rm -rf /tmp/cookies.txt

# Nexus
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1LAFetXJt-BwBC2hCCDoDorXeybIs-70O' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1LAFetXJt-BwBC2hCCDoDorXeybIs-70O" -O ./unsupervised/trained_models/nexus_mhd_model.pth.tar && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1UyQu-8uDqatWsS3woF1I3emmK0P2CJ31' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1UyQu-8uDqatWsS3woF1I3emmK0P2CJ31" -O ./unsupervised/trained_models/down_nexus_mhd_model.pth.tar && rm -rf /tmp/cookies.txt

# MUSE
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1tfeEVF7sUqa4yLi2ns-DMzJPsxqZiRDR' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1tfeEVF7sUqa4yLi2ns-DMzJPsxqZiRDR" -O ./unsupervised/trained_models/muse_mhd_model.pth.tar && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=18Qbun40IWyiA6sxpa0N00oS9bPiPRRFR' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=18Qbun40IWyiA6sxpa0N00oS9bPiPRRFR" -O ./unsupervised/trained_models/down_muse_mhd_model.pth.tar && rm -rf /tmp/cookies.txt
