# Pretrained models for the RL Experiment (Section 5.3)

# GMC
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1booMePEqi5_VGE88kC17v7kkAX7N3R1B' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1booMePEqi5_VGE88kC17v7kkAX7N3R1B" -O ./rl/trained_models/gmc_pendulum_model.pth.tar && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1o5FvFfpoDmT8q0feCMiw0pKfEhV4Ej6V' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1o5FvFfpoDmT8q0feCMiw0pKfEhV4Ej6V" -O ./rl/trained_models/down_gmc_pendulum_model.pth.tar && rm -rf /tmp/cookies.txt

# MVAE
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=16cGM4NsdtM6pfdGr7L2tGN3RozozzMml' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=16cGM4NsdtM6pfdGr7L2tGN3RozozzMml" -O ./rl/trained_models/mvae_pendulum_model.pth.tar && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1MyoBDj-VRoxTkjHfkEbKafEYzkoASpho' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1MyoBDj-VRoxTkjHfkEbKafEYzkoASpho" -O ./rl/trained_models/down_mvae_pendulum_model.pth.tar && rm -rf /tmp/cookies.txt

# GMC
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1gsttXLoHdt6y79okR8N_Mxc5I2oDTv7W' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1gsttXLoHdt6y79okR8N_Mxc5I2oDTv7W" -O ./rl/trained_models/muse_pendulum_model.pth.tar && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1OBwp5nTeWfcM_D83V84QRG4cXjJqOhNT' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1OBwp5nTeWfcM_D83V84QRG4cXjJqOhNT" -O ./rl/trained_models/down_muse_pendulum_model.pth.tar && rm -rf /tmp/cookies.txt
